### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(DesingStudio_01)
add_subdirectory(DesingStudio_01Content)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    DesingStudio_01plugin
    DesingStudio_01Contentplugin)